[theme]
primaryColor = "#0E7C86"
backgroundColor = "#EFF5F7"
secondaryBackgroundColor = "#F2F6F8"
textColor = "#16242B"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
